---
apiVersion: mongodbcommunity.mongodb.com/v1
kind: MongoDBCommunity
metadata:
  name: chat-mongodb
spec:
  members: 2
  type: ReplicaSet
  version: "6.0.5"
  security:
    authentication:
      modes: ["SCRAM"]
  users:
    - name: superuser
      db: admin
      passwordSecretRef: # a reference to the secret that will be used to generate the user's password
        name: superuser-password
      roles:
        - name: clusterAdmin
          db: admin
        - name: userAdminAnyDatabase
          db: admin
        - name: dbAdmin
          db: chat
        - name: readWrite
          db: chat  
      scramCredentialsSecretName: my-scram
  statefulSet:
    spec:
      template:
        spec:
          containers:
            - name: mongodb-agent
              readinessProbe:
                failureThreshold: 50
                initialDelaySeconds: 10
  additionalMongodConfig:
    storage.wiredTiger.engineConfig.journalCompressor: zlib



# the user credentials will be generated from this secret
# once the credentials are generated, this secret is no longer required

# For development purposes only. Not suitable for production.
---
apiVersion: v1
kind: Secret
metadata:
  name: superuser-password
type: Opaque
stringData:
  password: chatbackend123
