apiVersion: v1
kind: Service
metadata:
  name: mongodb-ext-0
  namespace: mongodb
spec:
  type: NodePort
  selector:
    app: chat-mongodb-svc
    statefulset.kubernetes.io/pod-name: chat-mongodb-0
  ports:
  - nodePort: 30017
    port: 27017
    protocol: TCP
    targetPort: 27017

---
apiVersion: v1
kind: Service
metadata:
  name: mongodb-ext-1
  namespace: mongodb
spec:
  type: NodePort
  selector:
    app: chat-mongodb-svc
    statefulset.kubernetes.io/pod-name: chat-mongodb-1
  ports:
  - nodePort: 31017
    port: 27017
    protocol: TCP
    targetPort: 27017
